default:
  ipfs:
    api: /ip4/127.0.0.1/tcp/5001
  eth:
    datadir: ~/.geth

development:
  eth:
    datadir: /mnt/u110/ethereum/pnet1
    account: '0x7116673528278887d37038d93bd749b66110ec35'
    password: dlheu0

test:

production:
